// Local search engine for the Docs & Support chat.
//
// PRIMARY answering path — no AI involved. The document chunks generated by
// tools/docs-extract.py are fetched once (static /specs-data/*.json) and
// searched in the browser. Only when nothing scores above the confidence
// threshold does the UI offer the AI fallback (see DocsPage).
//
// Matching strategy: the question is tokenized (Arabic + English aware) and
// chunks are scored by TOKEN COVERAGE — the fraction of meaningful query words
// found in the chunk text / document name / category. This handles long
// natural-language questions far better than fuzzy-matching the whole sentence.
// Fuse.js runs as a secondary fuzzy pass (typo tolerance) to gather context
// candidates when coverage is low.
import Fuse from "fuse.js";

export interface DocInfo {
  id: string;
  file: string; // static URL path, e.g. "specs/xxx.pdf"
  name: string;
  category: string;
  pages: number;
  kb: number;
}

export interface DocChunk {
  d: string; // doc id
  p: number; // page number
  t: string; // chunk text
}

export interface SearchHit {
  doc: DocInfo;
  page: number;
  /** Original (un-normalized) chunk text — safe to display. */
  text: string;
  /** 0 = perfect match … 1 = no match (1 − token coverage). */
  score: number;
}

export interface LocalResult {
  hits: SearchHit[];
  /** True when the best hit clears the confidence threshold. */
  confident: boolean;
}

// Answer directly from the documents when ≥ this fraction of the question's
// meaningful words are found in one chunk (+ its doc name/category).
export const CONFIDENT_COVERAGE = 0.65;

// ── Topics ────────────────────────────────────────────────────────────────
// User-facing topics for the chat's topic selector. `cats` are the raw manifest
// categories a topic covers; `terms` are the words/abbreviations a user might
// type (so "MVSG", "switch board", "CT/VT" all resolve to the right family);
// `anchors` are tokens present in the topic's document names, added to the query
// so retrieval reaches the right documents even from an abbreviation alone.
export interface Topic {
  id: string;
  label: string;
  emoji: string;
  cats: string[];
  terms: string[];
  anchors: string[];
}

export const TOPICS: Topic[] = [
  {
    id: "switchgear",
    label: "MV Switchgear (MVSG)",
    emoji: "⚡",
    cats: ["switch gears"],
    terms: ["switchgear", "switch gear", "mvsg", "mv sg", "switch board", "switchboard",
      "mv panel", "primary switchgear", "gis switchgear"],
    anchors: ["switchgear"],
  },
  {
    id: "rmu",
    label: "Ring Main Units (RMU)",
    emoji: "🔁",
    cats: ["RMU"],
    terms: ["rmu", "ring main unit", "ring main", "smart rmu"],
    anchors: ["rmu", "ring"],
  },
  {
    id: "breakers",
    label: "LV Circuit Breakers",
    emoji: "🔌",
    cats: ["low voltage circuit breakers up to 6300 A"],
    terms: ["circuit breaker", "breaker", "acb", "mccb", "mcb"],
    anchors: ["breaker", "circuit"],
  },
  {
    id: "lvpanels",
    label: "LV Panels",
    emoji: "🗄️",
    cats: ["Low Voltage Panels"],
    terms: ["lv panel", "low voltage panel", "panel board", "distribution board"],
    anchors: ["panel"],
  },
  {
    id: "pfc",
    label: "Power Factor Correction",
    emoji: "📈",
    cats: ["LOW VOLTAGE AUTOMATIC POWER FACTOR CORRECTION"],
    terms: ["power factor", "pfc", "capacitor bank", "apfc"],
    anchors: ["factor", "correction"],
  },
  {
    id: "transformers",
    label: "CT / VT Transformers",
    emoji: "🧲",
    cats: ["CT . VT"],
    terms: ["current transformer", "voltage transformer", "instrument transformer",
      "ct", "vt", "pt", "ct/vt"],
    anchors: ["transformer", "current", "voltage"],
  },
  {
    id: "kiosks",
    label: "Distribution Kiosks",
    emoji: "🏗️",
    cats: ["kiosks"],
    terms: ["kiosk", "package substation", "compact substation"],
    anchors: ["kiosk"],
  },
  {
    id: "meters",
    label: "Meters & Metering",
    emoji: "🔢",
    cats: ["METERS"],
    terms: ["meter", "metering", "smart meter", "prepaid meter", "mtu",
      "data concentrator", "kwh", "ami"],
    anchors: ["meter"],
  },
];

const TOPIC_BY_ID = new Map(TOPICS.map((t) => [t.id, t]));

export function topicById(id: string | null | undefined): Topic | undefined {
  return id ? TOPIC_BY_ID.get(id) : undefined;
}

/** Whole-word (plural-tolerant) test so "meter" doesn't match "parameter". */
function hasTerm(paddedNorm: string, term: string): boolean {
  const t = term.trim();
  return paddedNorm.includes(` ${t} `) || paddedNorm.includes(` ${t}s `);
}

/** Which topics does this question mention? Strongest first. Understands
 *  abbreviations / synonyms (MVSG, RMU, CT/VT, PFC, …). */
export function detectTopics(question: string): Topic[] {
  const nq = ` ${normalize(question)} `;
  return TOPICS.map((t) => ({
    t,
    hits: t.terms.reduce((n, term) => n + (hasTerm(nq, term) ? 1 : 0), 0),
  }))
    .filter((s) => s.hits > 0)
    .sort((a, b) => b.hits - a.hits)
    .map((s) => s.t);
}

interface IndexedChunk {
  d: string;
  p: number;
  t: string; // original text (display)
  nt: string; // normalized text (matching)
  docName: string;
  nDocName: string;
  nCategory: string;
  cDocName: string; // separator-free name (so "switchgear" matches "switch gears")
  cCategory: string; // separator-free category
  category: string; // raw manifest category (for topic scoping)
}

let dataPromise: Promise<{ docs: DocInfo[]; index: IndexedChunk[]; fuse: Fuse<IndexedChunk> }> | null =
  null;

/** Normalize Arabic variants + case + whitespace so matching works across forms. */
function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[ً-ْـ]/g, "") // Arabic diacritics + tatweel
    .replace(/[أإآ]/g, "ا")
    .replace(/ى/g, "ي")
    .replace(/ة/g, "ه")
    .replace(/\s+/g, " ")
    .trim();
}

/** Normalized text with ALL separators removed (spaces, dots, dashes), so a
 *  single-word query token like "switchgear" matches a spaced/punctuated name
 *  or category like "switch gears" or "CT . VT". */
function compact(s: string): string {
  return normalize(s).replace(/[^a-z0-9؀-ۿ]/g, "");
}

const STOPWORDS = new Set([
  // English
  "the", "of", "for", "and", "a", "an", "in", "on", "to", "is", "are", "be",
  "what", "whats", "which", "how", "much", "many", "does", "do", "can", "with",
  "about", "tell", "me", "please", "unit", "units",
  // Arabic
  "في", "من", "ما", "هو", "هي", "عن", "علي", "الي", "ان", "او", "كم", "هل", "مع",
]);

/** Split a question into meaningful, lightly-stemmed tokens. */
function tokenize(q: string): string[] {
  const raw = normalize(q).split(/[^a-z0-9؀-ۿ]+/).filter(Boolean);
  const out: string[] = [];
  for (let tok of raw) {
    if (tok.length < 2 || STOPWORDS.has(tok)) continue;
    // light stemming: English plural, Arabic definite article
    if (/^[a-z]+s$/.test(tok) && tok.length > 3) tok = tok.slice(0, -1);
    if (/^ال./.test(tok) && tok.length > 3) tok = tok.slice(2);
    if (tok.length >= 2 && !out.includes(tok)) out.push(tok);
  }
  return out;
}

/** Fetch manifest + chunks once and build the index (lazy, cached). */
export function loadDocsData() {
  if (!dataPromise) {
    dataPromise = (async () => {
      const [manifest, chunks] = await Promise.all([
        fetch("/specs-data/manifest.json").then((r) => {
          if (!r.ok) throw new Error("Could not load the document library.");
          return r.json() as Promise<DocInfo[]>;
        }),
        fetch("/specs-data/chunks.json").then((r) => {
          if (!r.ok) throw new Error("Could not load the document index.");
          return r.json() as Promise<DocChunk[]>;
        }),
      ]);
      const byId = new Map(manifest.map((d) => [d.id, d]));
      const index: IndexedChunk[] = chunks.map((c) => {
        const doc = byId.get(c.d);
        return {
          d: c.d,
          p: c.p,
          t: c.t,
          nt: normalize(c.t),
          docName: doc?.name ?? c.d,
          nDocName: normalize(doc?.name ?? c.d),
          nCategory: normalize(doc?.category ?? ""),
          cDocName: compact(doc?.name ?? c.d),
          cCategory: compact(doc?.category ?? ""),
          category: doc?.category ?? "",
        };
      });
      // Secondary fuzzy index (typo tolerance / low-coverage context gathering).
      const fuse = new Fuse(index, {
        keys: [
          { name: "nt", weight: 0.7 },
          { name: "nDocName", weight: 0.2 },
          { name: "nCategory", weight: 0.1 },
        ],
        includeScore: true,
        ignoreLocation: true,
        threshold: 0.4,
        useExtendedSearch: true,
        minMatchCharLength: 3,
      });
      return { docs: manifest, index, fuse };
    })();
    dataPromise.catch(() => {
      dataPromise = null; // allow retry after a failed load
    });
  }
  return dataPromise;
}

/** Search the local corpus. Instant — a lookup, not a network/AI call.
 *  Pass a `topicId` (from the chat's topic selector) to HARD-scope retrieval to
 *  one document family so answers never mix (e.g. an RMU spec can't answer a
 *  switchgear question). Omit it (or pass "all") to search everything with the
 *  topic auto-detected from the wording — including abbreviations like MVSG. */
export async function localSearch(
  question: string,
  limit = 5,
  topicId?: string
): Promise<LocalResult> {
  const { docs, index, fuse } = await loadDocsData();
  const byId = new Map(docs.map((d) => [d.id, d]));
  const tokens = tokenize(question);
  if (tokens.length === 0) return { hits: [], confident: false };

  // Topic scoping. An explicitly-picked topic hard-restricts retrieval to its
  // family; with no pick we auto-detect from the wording and apply a softer
  // affinity boost so the right family still leads.
  const picked = topicId && topicId !== "all" ? TOPIC_BY_ID.get(topicId) : undefined;
  const affinityTopic = picked ?? detectTopics(question)[0];
  const affinityCats = affinityTopic ? new Set(affinityTopic.cats) : null;
  const hardCats = picked ? new Set(picked.cats) : null;

  // Expand the query with the active topic's anchor words so the scorer reaches
  // that family's documents even when the user typed only an abbreviation.
  const searchTokens = [...tokens];
  if (affinityTopic)
    for (const a of affinityTopic.anchors)
      if (!searchTokens.includes(a)) searchTokens.push(a);

  type Scored = { c: IndexedChunk; coverage: number; density: number };
  const scoreAll = (restrict: Set<string> | null): Scored[] => {
    const out: Scored[] = [];
    for (const c of index) {
      if (restrict && !restrict.has(c.category)) continue;
      let matched = 0;
      let density = 0;
      let homeBoost = 0;
      for (const tok of searchTokens) {
        // Match the token against the document name / category in both their
        // spaced and separator-free forms, so "switchgear" matches the "switch
        // gears" category. A query word that names the document's own subject is
        // strong evidence it is ABOUT the question — boost it whether or not the
        // word also appears in this particular chunk's body.
        const inDocMeta =
          c.nDocName.includes(tok) ||
          c.nCategory.includes(tok) ||
          c.cDocName.includes(tok) ||
          c.cCategory.includes(tok);
        if (inDocMeta) homeBoost += 0.15;
        if (c.nt.includes(tok)) {
          matched++;
          // occurrences (capped) reward chunks that are ABOUT the topic
          let n = 0;
          let at = c.nt.indexOf(tok);
          while (at !== -1 && n < 5) {
            n++;
            at = c.nt.indexOf(tok, at + tok.length);
          }
          density += n;
        } else if (inDocMeta) {
          matched += 0.9; // found in the file name / category tag
        }
      }
      if (matched <= 0) continue;
      // Denominator is the user's real token count; anchors + boosts add on top.
      let coverage = matched / tokens.length + homeBoost;
      if (affinityCats && affinityCats.has(c.category)) coverage += 0.25; // on-topic family
      out.push({ c, coverage, density });
    }
    out.sort((a, b) => b.coverage - a.coverage || b.density - a.density);
    return out;
  };

  // Hard-scope when a topic is picked; if the question doesn't actually fit it
  // (no results at all), fall back to everything so the chat still answers.
  let scored = scoreAll(hardCats);
  if (hardCats && scored.length === 0) scored = scoreAll(null);

  // Diversify: at most 3 chunks per document so the AI sees several documents'
  // views of the topic instead of one file dominating the context.
  const perDoc = new Map<string, number>();
  const diverse: Scored[] = [];
  for (const s of scored) {
    const n = perDoc.get(s.c.d) ?? 0;
    if (n >= 3) continue;
    perDoc.set(s.c.d, n + 1);
    diverse.push(s);
    if (diverse.length >= limit) break;
  }
  let top = diverse;

  // Secondary: if coverage is weak, let Fuse gather fuzzy candidates (typos,
  // morphological variants). Keep them inside the picked topic when scoped.
  if ((top[0]?.coverage ?? 0) < CONFIDENT_COVERAGE) {
    try {
      const fuzzy = fuse.search(searchTokens.map((t) => `'${t}`).join(" | "), {
        limit: limit * 3,
      });
      for (const r of fuzzy) {
        if (hardCats && !hardCats.has(r.item.category)) continue;
        if (top.length >= limit) break;
        if (!top.some((s) => s.c === r.item)) {
          top.push({ c: r.item, coverage: Math.max(0, 0.5 - (r.score ?? 1) / 2), density: 0 });
        }
      }
      top = top.slice(0, limit);
    } catch {
      /* extended-search parse issue — coverage results stand alone */
    }
  }

  const hits: SearchHit[] = top
    .map((s) => ({
      doc: byId.get(s.c.d)!,
      page: s.c.p,
      text: s.c.t,
      score: 1 - Math.min(1, s.coverage),
    }))
    .filter((h) => h.doc);

  const confident =
    hits.length > 0 &&
    (tokens.length === 1 ? hits[0].score <= 0.35 : 1 - hits[0].score >= CONFIDENT_COVERAGE);

  return { hits, confident };
}
