// Local search engine for the Docs & Support chat.
//
// PRIMARY answering path — no AI involved. The document chunks generated by
// tools/docs-extract.py are fetched once (static /specs-data/*.json) and
// searched in the browser. Only when nothing scores above the confidence
// threshold does the UI offer the AI fallback (see DocsPage).
//
// Matching strategy: the question is tokenized (Arabic + English aware) and
// chunks are scored by TOKEN COVERAGE — the fraction of meaningful query words
// found in the chunk text / document name / category. This handles long
// natural-language questions far better than fuzzy-matching the whole sentence.
// Fuse.js runs as a secondary fuzzy pass (typo tolerance) to gather context
// candidates when coverage is low.
import Fuse from "fuse.js";

export interface DocInfo {
  id: string;
  file: string; // static URL path, e.g. "specs/xxx.pdf"
  name: string;
  category: string;
  pages: number;
  kb: number;
}

export interface DocChunk {
  d: string; // doc id
  p: number; // page number
  t: string; // chunk text
}

export interface SearchHit {
  doc: DocInfo;
  page: number;
  /** Original (un-normalized) chunk text — safe to display. */
  text: string;
  /** 0 = perfect match … 1 = no match (1 − token coverage). */
  score: number;
}

export interface LocalResult {
  hits: SearchHit[];
  /** True when the best hit clears the confidence threshold. */
  confident: boolean;
}

// Answer directly from the documents when ≥ this fraction of the question's
// meaningful words are found in one chunk (+ its doc name/category).
export const CONFIDENT_COVERAGE = 0.65;

interface IndexedChunk {
  d: string;
  p: number;
  t: string; // original text (display)
  nt: string; // normalized text (matching)
  docName: string;
  nDocName: string;
  nCategory: string;
}

let dataPromise: Promise<{ docs: DocInfo[]; index: IndexedChunk[]; fuse: Fuse<IndexedChunk> }> | null =
  null;

/** Normalize Arabic variants + case + whitespace so matching works across forms. */
function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[ً-ْـ]/g, "") // Arabic diacritics + tatweel
    .replace(/[أإآ]/g, "ا")
    .replace(/ى/g, "ي")
    .replace(/ة/g, "ه")
    .replace(/\s+/g, " ")
    .trim();
}

const STOPWORDS = new Set([
  // English
  "the", "of", "for", "and", "a", "an", "in", "on", "to", "is", "are", "be",
  "what", "whats", "which", "how", "much", "many", "does", "do", "can", "with",
  "about", "tell", "me", "please", "unit", "units",
  // Arabic
  "في", "من", "ما", "هو", "هي", "عن", "علي", "الي", "ان", "او", "كم", "هل", "مع",
]);

/** Split a question into meaningful, lightly-stemmed tokens. */
function tokenize(q: string): string[] {
  const raw = normalize(q).split(/[^a-z0-9؀-ۿ]+/).filter(Boolean);
  const out: string[] = [];
  for (let tok of raw) {
    if (tok.length < 2 || STOPWORDS.has(tok)) continue;
    // light stemming: English plural, Arabic definite article
    if (/^[a-z]+s$/.test(tok) && tok.length > 3) tok = tok.slice(0, -1);
    if (/^ال./.test(tok) && tok.length > 3) tok = tok.slice(2);
    if (tok.length >= 2 && !out.includes(tok)) out.push(tok);
  }
  return out;
}

/** Fetch manifest + chunks once and build the index (lazy, cached). */
export function loadDocsData() {
  if (!dataPromise) {
    dataPromise = (async () => {
      const [manifest, chunks] = await Promise.all([
        fetch("/specs-data/manifest.json").then((r) => {
          if (!r.ok) throw new Error("Could not load the document library.");
          return r.json() as Promise<DocInfo[]>;
        }),
        fetch("/specs-data/chunks.json").then((r) => {
          if (!r.ok) throw new Error("Could not load the document index.");
          return r.json() as Promise<DocChunk[]>;
        }),
      ]);
      const byId = new Map(manifest.map((d) => [d.id, d]));
      const index: IndexedChunk[] = chunks.map((c) => {
        const doc = byId.get(c.d);
        return {
          d: c.d,
          p: c.p,
          t: c.t,
          nt: normalize(c.t),
          docName: doc?.name ?? c.d,
          nDocName: normalize(doc?.name ?? c.d),
          nCategory: normalize(doc?.category ?? ""),
        };
      });
      // Secondary fuzzy index (typo tolerance / low-coverage context gathering).
      const fuse = new Fuse(index, {
        keys: [
          { name: "nt", weight: 0.7 },
          { name: "nDocName", weight: 0.2 },
          { name: "nCategory", weight: 0.1 },
        ],
        includeScore: true,
        ignoreLocation: true,
        threshold: 0.4,
        useExtendedSearch: true,
        minMatchCharLength: 3,
      });
      return { docs: manifest, index, fuse };
    })();
    dataPromise.catch(() => {
      dataPromise = null; // allow retry after a failed load
    });
  }
  return dataPromise;
}

/** Search the local corpus. Instant — a lookup, not a network/AI call. */
export async function localSearch(question: string, limit = 5): Promise<LocalResult> {
  const { docs, index, fuse } = await loadDocsData();
  const byId = new Map(docs.map((d) => [d.id, d]));
  const tokens = tokenize(question);
  if (tokens.length === 0) return { hits: [], confident: false };

  // Primary: token-coverage scoring over every chunk. Chunks living in a
  // category/document whose NAME matches the question get a boost, so
  // "switchgear" questions rank switch-gear specs above other docs that merely
  // mention the word.
  type Scored = { c: IndexedChunk; coverage: number; density: number };
  const scored: Scored[] = [];
  for (const c of index) {
    let matched = 0;
    let density = 0;
    let homeBoost = 0;
    for (const tok of tokens) {
      const inDocMeta = c.nDocName.includes(tok) || c.nCategory.includes(tok);
      if (c.nt.includes(tok)) {
        matched++;
        if (inDocMeta) homeBoost += 0.08; // topic word AND it's that doc's subject
        // occurrences (capped) reward chunks that are ABOUT the topic
        let n = 0;
        let at = c.nt.indexOf(tok);
        while (at !== -1 && n < 5) {
          n++;
          at = c.nt.indexOf(tok, at + tok.length);
        }
        density += n;
      } else if (inDocMeta) {
        matched += 0.9; // found in the file name / category tag
      }
    }
    if (matched > 0)
      scored.push({ c, coverage: matched / tokens.length + homeBoost, density });
  }
  scored.sort((a, b) => b.coverage - a.coverage || b.density - a.density);

  // Diversify: at most 3 chunks per document so the AI sees several documents'
  // views of the topic instead of one file dominating the context.
  const perDoc = new Map<string, number>();
  const diverse: Scored[] = [];
  for (const s of scored) {
    const n = perDoc.get(s.c.d) ?? 0;
    if (n >= 3) continue;
    perDoc.set(s.c.d, n + 1);
    diverse.push(s);
    if (diverse.length >= limit) break;
  }
  let top = diverse;

  // Secondary: if coverage is weak, let Fuse gather fuzzy candidates (typos,
  // morphological variants) so the AI escalation still gets grounded context.
  if ((top[0]?.coverage ?? 0) < CONFIDENT_COVERAGE) {
    try {
      const fuzzy = fuse.search(tokens.map((t) => `'${t}`).join(" | "), { limit });
      for (const r of fuzzy) {
        if (!top.some((s) => s.c === r.item)) {
          top.push({ c: r.item, coverage: Math.max(0, 0.5 - (r.score ?? 1) / 2), density: 0 });
        }
      }
      top = top.slice(0, limit);
    } catch {
      /* extended-search parse issue — coverage results stand alone */
    }
  }

  const hits: SearchHit[] = top
    .map((s) => ({
      doc: byId.get(s.c.d)!,
      page: s.c.p,
      text: s.c.t,
      score: 1 - Math.min(1, s.coverage),
    }))
    .filter((h) => h.doc);

  const confident =
    hits.length > 0 &&
    (tokens.length === 1 ? hits[0].score <= 0.35 : 1 - hits[0].score >= CONFIDENT_COVERAGE);

  return { hits, confident };
}
